name: Test snapshot/snapshot schedule ds/rs

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - 'v*'
    paths:
      - "**.go"
      - ".github/workflows/snapshot.yml"
  pull_request:
    branches:
      - master
      - 'v*'
    paths:
      - "**gridscale_snapshot**"
      - "gridscale/error-handler/**"
      - "gridscale/common.go"
      - "gridscale/config.go"
      - "gridscale/provider.go"
      - "gridscale/provider_test.go"
      - ".github/workflows/snapshot.yml"

jobs:
  build:
    name: Snapshot/Snapshot schedule AccTest
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      GRIDSCALE_UUID: ${{ secrets.CI_USER_UUID }}
      GRIDSCALE_TOKEN: ${{ secrets.CI_API_TOKEN }}
      GRIDSCALE_URL: ${{ secrets.CI_API_URL }}
      GRIDSCALE_TF_REQUEST_DELAY_INTERVAL: 2000
      GRIDSCALE_TF_MAX_N_RETRIES: 5
    steps:
      - name: Set up Go 1.24
        uses: actions/setup-go@v6
        with:
          go-version: ^1.24
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v6

      - name: Run TestAccdataSourceGridscaleSnapshotBasic
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccdataSourceGridscaleSnapshotBasic'

      - name: Run TestAccdataSourceGridscaleSnapshotScheduleBasic
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccdataSourceGridscaleSnapshotScheduleBasic'

      - name: Run TestAccResourceGridscaleSnapshotBasic
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccResourceGridscaleSnapshotBasic'

      - name: Run TestAccResourceGridscaleSnapshotScheduleBasic
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccResourceGridscaleSnapshotScheduleBasic'
